development:

  <<: *default
  database: onlineSticker_development

  adapter: mysql2
  encoding: utf8
  database: OnlineSticker_development
  pool: 5
  username: root
  
  password: root


test:
  development:
  adapter: mysql2
  encoding: utf8
  database: OnlineSticker_test
  pool: 5
  username: root
  password: root

production:
 development:
  adapter: mysql2
  encoding: utf8
  database: OnlineSticker_production
  pool: 5
  username: root
  password: root
  
